import * as lark from '@larksuiteoapi/node-sdk';
import {
  CardBuilder,
  CardConfigBuilder,
  CardHeaderBuilder,
  CardBodyBuilder,
  CardLinkBuilder,
  FallbackBuilder,
  ButtonBuilder,
  InputBuilder,
  SelectBuilder,
  DatePickerBuilder,
  CheckboxBuilder,
  ImageBuilder,
  DivBuilder,
  FormBuilder,
  ColumnSetBuilder,
  ColumnBuilder,
  HrBuilder,
  PlainTextBuilder,
  MarkdownBuilder,
  TableBuilder,
  TableColumnBuilder,
  TableHeaderStyleBuilder,
  TableNumberFormatBuilder,
  PersonBuilder,
  PersonListBuilder,
  PickerTimeBuilder,
  PickerDatetimeBuilder,
  SelectPersonBuilder,
  MultiSelectPersonBuilder,
  OverflowBuilder,
  CheckerBuilder,
  ImgCombinationBuilder,
  InteractiveContainerBuilder,
  TextTagBuilder,
  ButtonType,
  ButtonSize,
  InputType,
  ImageSize,
  SpacingSize,
  AlignType,
  BehaviorType,
  toJson,
  toJsonWithNull,
  TemplateParameterFiller,
  ElementFinder,
  template
} from '../../LarkCardKit/dist/esm/index.js';

const client = new lark.Client({
  appId: process.env.APP_ID!,
  appSecret: process.env.APP_SECRET!
});
